# Generated by Django 6.0.4 on 2026-04-14 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='educationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Degree', models.CharField(max_length=100)),
                ('Institution', models.CharField(max_length=100)),
                ('graduationYear', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='resumeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProfilePicture', models.ImageField(upload_to='static/profilePicture')),
                ('FullName', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('CareerObjective', models.TextField()),
                ('Skills', models.CharField(max_length=100)),
                ('Certification', models.CharField(max_length=100)),
                ('Projects', models.CharField(max_length=100)),
                ('References', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='workModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('StartDate', models.CharField(max_length=100)),
                ('EndDate', models.CharField(max_length=100)),
            ],
        ),
    ]
