# Generated by Django 6.0.4 on 2026-06-07 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='product_img',
            field=models.ImageField(blank=True, null=True, upload_to='media/product_imgs'),
        ),
    ]
