# Generated by Django 6.0.4 on 2026-06-09 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0002_alter_productmodel_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='total_amount',
            field=models.FloatField(null=True),
        ),
    ]
