# Generated by Django 6.0.4 on 2026-06-22 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_taskmodel_created_at_alter_taskmodel_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
