# Generated by Django 6.0.3 on 2026-04-21 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='ProfilePicture',
            field=models.ImageField(null=True, upload_to='static/profile-picture'),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='City',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='Department',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='FirstName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='LastName',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
