# Generated by Django 6.0.3 on 2026-04-06 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='teacherModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacherName', models.CharField(max_length=50)),
                ('teacherid', models.CharField(max_length=50)),
                ('teacherType', models.CharField(max_length=50)),
            ],
        ),
    ]
