# Generated by Django 6.0.3 on 2026-04-07 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_teachermodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmodel',
            name='department',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='name',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='rollNo',
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='City',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='FirstName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='LastName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='Department',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
